name: PR Preview

on:
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 18

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ env.NODE_VERSION }}
          cache-dependency-path: pnpm-lock.yaml

      - name: Install npm deps
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Create preview
        uses: filoozom/swarm-actions/pr-preview@v0
        with:
          dir: ./dist
          error-document: index.html
