name: Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 18

    steps:
      - name: Install pnpm
        run: curl -fsSL https://get.pnpm.io/install.sh | sh -

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ env.NODE_VERSION }}
          cache-dependency-path: pnpm-lock.yaml

      - name: Install npm deps
        run: pnpm i --frozen-lockfile

      - name: Run linting test
        run: pnpm run lint
